const webDev = [
  {
    borderColor: "border-orange-500",
    gradientColors: "from-orange-500 to-orange-400",
    textColor: "orange-500",
    shadowColor: "shadow-orange-500",
    imageURL: "/assets/skills/html.png",
    content: "HTML",
  },
  {
    borderColor: "border-blue-500",
    gradientColors: "from-blue-500 to-blue-400",
    textColor: "blue-500",
    shadowColor: "shadow-blue-500",
    imageURL: "/assets/skills/css.png",
    content: "CSS",
  },
  {
    borderColor: "border-yellow-500",
    gradientColors: "from-yellow-500 to-yellow-400",
    textColor: "yellow-500",
    shadowColor: "shadow-yellow-500",
    imageURL: "/assets/skills/javascript.png",
    content: "JavaScript",
  },
  {
    borderColor: "border-blue-600",
    gradientColors: "from-blue-600 to-blue-500",
    textColor: "blue-500",
    shadowColor: "shadow-blue-500",
    imageURL: "/assets/skills/typescript.png",
    content: "TypeScript",
  },
  {
    borderColor: "border-blue-400",
    gradientColors: "from-blue-400 to-cyan-400",
    textColor: "blue-500",
    shadowColor: "shadow-blue-500",
    imageURL: "/assets/skills/react.png",
    content: "React",
  },
  {
    borderColor: "border-gray-500",
    gradientColors: "from-gray-500 to-gray-400",
    textColor: "gray-500",
    shadowColor: "shadow-gray-500",
    imageURL: "/assets/skills/next-js-new.svg",
    content: "Next",
  },
  {
    borderColor: "border-cyan-500",
    gradientColors: "from-cyan-500 to-cyan-400",
    textColor: "cyan-500",
    shadowColor: "shadow-cyan-500",
    imageURL: "/assets/skills/tailwindcss.png",
    content: "Tailwind",
  },
  {
    borderColor: "border-green-500",
    gradientColors: "from-green-500 to-green-400",
    textColor: "green-500",
    shadowColor: "shadow-green-500",
    imageURL: "/assets/skills/mongodb.png",
    content: "MongoDB",
  },
];

const blockChainDev = [
  {
    borderColor: "border-gray-500",
    gradientColors: "from-gray-500 to-black",
    textColor: "gray-500",
    shadowColor: "shadow-gray-500",
    imageURL: "/assets/skills/solidity.svg",
    content: "Solidity",
  },
  {
    borderColor: "border-yellow-600",
    gradientColors: "from-yellow-500 to-yellow-400",
    textColor: "yellow-500",
    shadowColor: "shadow-yellow-600",
    imageURL: "/assets/skills/hardhat.svg",
    content: "HardHat",
  },
  {
    borderColor: "border-blue-700",
    gradientColors: "from-blue-800 to-blue-600",
    textColor: "blue-500",
    shadowColor: "shadow-blue-700",
    imageURL: "/assets/skills/ethers.svg",
    content: "Ethers.js",
  },
  {
    borderColor: "border-cyan-700",
    gradientColors: "from-cyan-700 to-cyan-600",
    textColor: "blue-500",
    shadowColor: "shadow-cyan-700",
    imageURL: "/assets/skills/Ipfs.png",
    content: "IPFS",
  },
];
export default { webDev, blockChainDev };
