
import './globals.css'
import {Pirata_One, Sansita} from "@next/font/google"
import { Poppins } from '@next/font/google'

const pirata = Pirata_One({weight:'400',subsets:["latin"]})
const poppins = Poppins({weight:'400',subsets:["latin"]})
export const metadata = {
  title: 'Sai - Portfolio Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`${pirata.className}`}>
        {children}</body>
    </html>
  )
}
